-- Deleting a screen should free its numeric id for reuse (so the URL
-- namespace doesn't just count up forever as TVs get reconfigured), rather
-- than the default identity-column behavior of always incrementing.

-- BY DEFAULT (vs ALWAYS) lets an explicit id be supplied on insert without
-- needing the OVERRIDING SYSTEM VALUE clause.
alter table screens alter column id set generated by default;

-- Smallest positive integer not currently in use, e.g. {1,2,4} -> 3, {1,2,3} -> 4.
create or replace function next_free_screen_id()
returns bigint language sql stable as $$
  select min(s.id)
  from generate_series(1, (select coalesce(max(id), 0) from screens) + 1) as s(id)
  where s.id not in (select id from screens);
$$;
